version: "2"
services:
  ofada-app:
    container_name: ofada-server
    restart: always
    build: .
    ports:
      - "4000:8000"
    links:
      - database
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"